import { ModalProvider } from "@/context/ModalContext";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import ConfigPopover from "@/components/ConfigPopover";
import { ConfigProvider } from "@/context/ConfigContext";

const MontserratFont = Montserrat({
  weight: ["400"],
  subsets: ['vietnamese']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${MontserratFont.className} antialiased`}>
        <div>
          <ConfigProvider>
            <AppProvider>
              <div style={{zIndex:1}} className="absolute top-4 right-4">
                <ConfigPopover />
              </div>
              <ModalProvider>{children}</ModalProvider>
            </AppProvider>
          </ConfigProvider>
        </div>
      </body>
    </html>
  );
}
