import { ModalProvider } from "@/context/ModalContext";
import type { Metadata } from "next";
import { Coiny } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import ConfigPopover from "@/components/ConfigPopover";
import { ConfigProvider } from "@/context/ConfigContext";

const coinyFont = Coiny({
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${coinyFont.className} antialiased`}>
        <ConfigProvider>
          <AppProvider>
            <div className="absolute top-4 right-4">
              <ConfigPopover />
            </div>
            <ModalProvider>{children}</ModalProvider>
          </AppProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
